[package]
name = "wit-bindgen-cli"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version.workspace = true
edition.workspace = true

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/wit-bindgen-demo",
  "crates/wit-component",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.2.0"

[workspace.dependencies]
anyhow = "1.0.65"
bitflags = "1.3.2"
heck = "0.3"
pulldown-cmark = { version = "0.8", default-features = false }
clap = { version = "4.0.9", features = ["derive"] }

wasmtime = "1.0"
wasmtime-wasi = "1.0"
wasmprinter = "0.2.40"
wasmparser = "0.91.0"
wasm-encoder = "0.17.0"
wat = "1.0.49"

wit-bindgen-core = { path = 'crates/bindgen-core', version = '0.2.0' }
wit-bindgen-gen-guest-c = { path = 'crates/gen-guest-c', version = '0.2.0' }
wit-bindgen-gen-guest-rust = { path = "crates/gen-guest-rust", version = "0.2.0", default-features = false }
wit-bindgen-gen-guest-teavm-java = { path = 'crates/gen-guest-teavm-java', version = '0.2.0' }
wit-bindgen-gen-host-js = { path = 'crates/gen-host-js', version = '0.2.0' }
wit-bindgen-gen-host-wasmtime-py = { path = 'crates/gen-host-wasmtime-py', version = '0.2.0' }
wit-bindgen-gen-host-wasmtime-rust = { path = 'crates/gen-host-wasmtime-rust', version = '0.2.0' }
wit-bindgen-gen-markdown = { path = 'crates/gen-markdown', version = '0.2.0' }
wit-bindgen-gen-rust-lib = { path = 'crates/gen-rust-lib', version = '0.2.0', default-features = false }
wit-bindgen-guest-rust = { path = 'crates/guest-rust', version = '0.2.0', default-features = false }
wit-bindgen-host-wasmtime-rust = { path = 'crates/host-wasmtime-rust', version = '0.2.0' }
wit-parser = { path = 'crates/wit-parser', version = '0.2.0' }

[[bin]]
name = "wit-bindgen"
test = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
wit-bindgen-core = { path = 'crates/bindgen-core' }
wit-bindgen-gen-guest-rust = { path = 'crates/gen-guest-rust', features = ['clap'] }
wit-bindgen-gen-host-wasmtime-rust = { path = 'crates/gen-host-wasmtime-rust', features = ['clap'] }
wit-bindgen-gen-host-wasmtime-py = { path = 'crates/gen-host-wasmtime-py', features = ['clap'] }
wit-bindgen-gen-host-js = { path = 'crates/gen-host-js', features = ['clap'] }
wit-bindgen-gen-guest-c = { path = 'crates/gen-guest-c', features = ['clap'] }
wit-bindgen-gen-markdown = { path = 'crates/gen-markdown', features = ['clap'] }
wit-bindgen-gen-guest-teavm-java = { path = 'crates/gen-guest-teavm-java', features = ['clap'] }
