[package]
name = "wit-bindgen-cli"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.8.0"
edition = { workspace = true }
repository = 'https://github.com/bytecodealliance/wit-bindgen'
license = "Apache-2.0 WITH LLVM-exception"
homepage = 'https://github.com/bytecodealliance/wit-bindgen'
description = """
CLI tool to generate bindings for WIT documents and the component model.
"""

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/wasi_snapshot_preview1",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.70"
bitflags = "2.1.0"
heck =  { version = "0.4", features = ["unicode"] }
pulldown-cmark = { version = "0.9.3", default-features = false }
clap = { version = "4.2.2", features = ["derive"] }
env_logger = "0.10.0"
indexmap = "1.9.3"

wasm-encoder = "0.29.0"
wasm-metadata = { git = "https://github.com/bytecodealliance/wasm-tools" }
wat =  { git = "https://github.com/bytecodealliance/wasm-tools" }
wit-parser = { git = "https://github.com/bytecodealliance/wasm-tools" }
wit-component =  { git = "https://github.com/bytecodealliance/wasm-tools" }

wit-bindgen-core = { path = 'crates/core', version = '0.8.0' }
wit-bindgen-c = { path = 'crates/c', version = '0.8.0' }
wit-bindgen-rust = { path = "crates/rust", version = "0.8.0" }
wit-bindgen-teavm-java = { path = 'crates/teavm-java', version = '0.8.0' }
wit-bindgen-go = { path = 'crates/go', version = '0.6.0' }
wit-bindgen-markdown = { path = 'crates/markdown', version = '0.8.0' }
wit-bindgen-rust-lib = { path = 'crates/rust-lib', version = '0.8.0' }
wit-bindgen = { path = 'crates/guest-rust', version = '0.8.0', default-features = false }
wit-bindgen-rust-macro-shared = { path = 'crates/rust-macro-shared', version = '0.3.0' }

[[bin]]
name = "wit-bindgen"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
wit-bindgen-core = { workspace = true }
wit-bindgen-rust = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-c = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-markdown = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-teavm-java = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-go = { workspace = true, features = ['clap'], optional = true }
wat = { workspace = true }
wit-component = { workspace = true }
wasm-encoder = { workspace = true }

[features]
default = [
  'c',
  'rust',
  'markdown',
  'teavm-java',
  'go',
]
c = ['dep:wit-bindgen-c']
rust = ['dep:wit-bindgen-rust']
markdown = ['dep:wit-bindgen-markdown']
teavm-java = ['dep:wit-bindgen-teavm-java']
go = ['dep:wit-bindgen-go']

[dev-dependencies]
heck = { workspace = true }
wasmtime = { git = "https://github.com/dicej/wasmtime", branch = "resources", features = ["component-model"] } #{ version = "10", features = ['component-model'] }
test-artifacts = { path = 'crates/test-rust-wasm/artifacts' }
wit-parser = { workspace = true }
