[package]
name = "wit-bindgen-guest-rust"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version.workspace = true
edition.workspace = true

[dependencies]
wit-bindgen-guest-rust-macro = { path = "../guest-rust-macro", optional = true, default-features = false }
bitflags = { workspace = true }

[features]
default = ["macros", "std"]
macros = ["wit-bindgen-guest-rust-macro"]
std = ["wit-bindgen-guest-rust-macro/std"]
